# Generated by Django 6.0.7 on 2026-07-21 17:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(help_text='Haqqımızda səhifəsinin böyük vizual şəkli. Yükləyəndə avtomatik sıxılır.', upload_to='images/about/banners/', verbose_name='Banner şəkil')),
                ('intro_title_az', models.CharField(help_text='Məsələn: DigiBoom-u yaxından tanıyın', max_length=120, verbose_name='Intro başlıq (AZ)')),
                ('intro_title_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Intro başlıq (EN)')),
                ('intro_title_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Intro başlıq (RU)')),
                ('intro_text_az', models.TextField(help_text='Video yanındakı və ya intro blokundakı əsas mətn (HTML).', validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Intro mətn (AZ)')),
                ('intro_text_en', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Intro mətn (EN)')),
                ('intro_text_ru', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Intro mətn (RU)')),
                ('video', models.FileField(blank=True, help_text='Haqqımızda səhifəsində play düyməsi ilə açılan video. Yalnız bir fayl.', null=True, upload_to='videos/about/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp4', 'webm', 'mov', 'ogg', 'mkv'), message='İcazə verilən formatlar: mp4, webm, mov, ogg, mkv.')], verbose_name='Tanıtım videosu')),
                ('video_poster', models.ImageField(blank=True, help_text='Video oynatılmadan əvvəl görünən şəkil. İstəyə bağlı.', null=True, upload_to='images/about/video_posters/', verbose_name='Video örtüyü (poster)')),
                ('home_teaser_az', models.TextField(help_text='Ana səhifədəki «Haqqımızda» bloku — bir mətn bloku (HTML).', validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Ana səhifə teaser (AZ)')),
                ('home_teaser_en', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Ana səhifə teaser (EN)')),
                ('home_teaser_ru', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Ana səhifə teaser (RU)')),
            ],
            options={
                'verbose_name': 'Haqqımızda səhifəsi',
                'verbose_name_plural': 'Haqqımızda səhifəsi',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.CharField(max_length=120, verbose_name='Ad (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ad (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ad (RU)')),
                ('logo', models.ImageField(help_text='Tərəfdaş/müştəri loqosu. Yükləyəndə avtomatik sıxılır.', upload_to='images/partners/', verbose_name='Loqo')),
                ('url', models.URLField(blank=True, help_text='İstəyə bağlı — loqoya klikdə açılacaq ünvan.', null=True, verbose_name='Link (URL)')),
                ('is_active', models.BooleanField(default=True, help_text='Söndürsəniz loqo heç yerdə görünməz.', verbose_name='Saytda göstərilsin?')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk. Kiçik rəqəm əvvəl göstərilir.', verbose_name='Sıra')),
                ('show_on_about', models.BooleanField(default=True, help_text='Haqqımızda səhifəsinin tərəfdaşlar blokunda göstərilsin.', verbose_name='Haqqımızda səhifəsində?')),
            ],
            options={
                'verbose_name': 'Tərəfdaş',
                'verbose_name_plural': 'Tərəfdaşlar',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StatisticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Məsələn: 25, 90+, 150.', max_length=32, verbose_name='Rəqəm / dəyər')),
                ('label_az', models.CharField(help_text='Rəqəmin altında görünən qısa mətn. Məs: Tamamlanmış layihə', max_length=120, verbose_name='Alt yazı (AZ)')),
                ('label_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Alt yazı (EN)')),
                ('label_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Alt yazı (RU)')),
                ('icon', models.CharField(blank=True, choices=[('lucide:calendar-check', 'Təcrübə / illər'), ('lucide:users', 'Müştərilər / komanda'), ('lucide:briefcase', 'Layihələr'), ('lucide:award', 'Mükafat'), ('lucide:trending-up', 'Artım'), ('lucide:globe', 'Ölkə / region'), ('lucide:thumbs-up', 'Məmnuniyyət'), ('lucide:star', 'Reytinq'), ('lucide:handshake', 'Tərəfdaşlıq'), ('lucide:rocket', 'Start / sürət'), ('lucide:graduation-cap', 'Təlim / Academy'), ('lucide:heart', 'Sevgi / loyallıq')], help_text='Kartda görünən Iconify (Lucide) ikonu.', max_length=64, null=True, verbose_name='İkon')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk. Kiçik rəqəm əvvəl göstərilir.', verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, help_text='Söndürsəniz heç yerdə görünməz.', verbose_name='Saytda göstərilsin?')),
                ('show_on_about', models.BooleanField(default=True, verbose_name='Haqqımızda səhifəsində?')),
                ('show_on_home', models.BooleanField(default=True, verbose_name='Ana səhifədə?')),
            ],
            options={
                'verbose_name': 'Statistika elementi',
                'verbose_name_plural': 'Statistika elementləri',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AboutGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Qalereya şəkli. Yükləyəndə avtomatik sıxılır.', upload_to='images/about/gallery/', verbose_name='Şəkil')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk. Kiçik rəqəm əvvəl göstərilir.', verbose_name='Sıra')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.about', verbose_name='Haqqımızda səhifəsi')),
            ],
            options={
                'verbose_name': 'Qaleriya şəkli',
                'verbose_name_plural': 'Qaleriya şəkilləri',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_az', models.CharField(max_length=120, verbose_name='Başlıq (AZ)')),
                ('title_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Başlıq (EN)')),
                ('title_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Başlıq (RU)')),
                ('body_az', models.TextField(help_text='Kartın içindəki mətn (HTML).', validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Məzmun (AZ)')),
                ('body_en', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Məzmun (EN)')),
                ('body_ru', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Məzmun (RU)')),
                ('icon', models.CharField(blank=True, choices=[('lucide:briefcase', 'Agentlik / iş'), ('lucide:graduation-cap', 'Academy / təlim'), ('lucide:sparkles', 'Missiya / dəyərlər'), ('lucide:target', 'Hədəf'), ('lucide:users', 'Komanda'), ('lucide:lightbulb', 'İdeya'), ('lucide:rocket', 'Artım / start'), ('lucide:heart', 'Dəyərlər'), ('lucide:award', 'Mükafat / keyfiyyət'), ('lucide:globe', 'Qlobal / region'), ('lucide:code-2', 'Texnologiya'), ('lucide:palette', 'Dizayn / brend')], help_text='Kartda görünən Iconify (Lucide) ikonu.', max_length=64, null=True, verbose_name='İkon')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk. Kiçik rəqəm əvvəl göstərilir.', verbose_name='Sıra')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.about', verbose_name='Haqqımızda səhifəsi')),
            ],
            options={
                'verbose_name': 'Haqqımızda bölməsi',
                'verbose_name_plural': 'Haqqımızda bölmələri',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
