# Generated by Django 6.0.7 on 2026-07-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_about_admin_consolidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='video_poster',
        ),
    ]
