# Generated by Django 6.0.7 on 2026-07-21 18:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_about_video_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Ana səhifə'), ('about', 'Haqqımızda'), ('services', 'Xidmətlər'), ('portfolio', 'Portfolio'), ('training', 'Təlimlər'), ('blog', 'Bloq'), ('contact', 'Əlaqə'), ('privacy', 'Məxfilik siyasəti'), ('terms', 'İstifadə şərtləri')], help_text='Hansı səhifənin headeri. Hər səhifə üçün yalnız bir qeyd.', max_length=32, unique=True, verbose_name='Səhifə')),
                ('motto_az', models.TextField(blank=True, help_text='Header altındakı qısa şüar / tagline (HTML).', validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Deviz (AZ)')),
                ('motto_en', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Deviz (EN)')),
                ('motto_ru', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Deviz (RU)')),
                ('image', models.ImageField(blank=True, help_text='Ana səhifə XARİCində header fon şəkli. Ana səhifə üçün media inline-dan (şəkil/video) əlavə edin — bu sahə istifadə olunmur.', null=True, upload_to='images/page_headers/', verbose_name='Header şəkli')),
            ],
            options={
                'verbose_name': 'Səhifə headeri',
                'verbose_name_plural': 'Səhifə headerləri',
                'ordering': ('page',),
            },
        ),
        migrations.RemoveField(
            model_name='about',
            name='banner',
        ),
        migrations.CreateModel(
            name='HomeHeroMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Şəkil'), ('video', 'Video')], max_length=16, verbose_name='Media tipi')),
                ('image', models.ImageField(blank=True, help_text='media_type = Şəkil olduqda məcburi. Yükləyəndə avtomatik sıxılır.', null=True, upload_to='images/page_headers/home/', verbose_name='Şəkil')),
                ('video', models.FileField(blank=True, help_text='media_type = Video olduqda məcburi.', null=True, upload_to='videos/page_headers/home/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp4', 'webm', 'mov', 'ogg', 'mkv'), message='İcazə verilən formatlar: mp4, webm, mov, ogg, mkv.')], verbose_name='Video')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk slayd. Kiçik rəqəm əvvəl başlayır.', verbose_name='Sıra')),
                ('header', models.ForeignKey(limit_choices_to={'page': 'home'}, on_delete=django.db.models.deletion.CASCADE, related_name='home_media', to='core.pageheader', verbose_name='Ana səhifə headeri')),
            ],
            options={
                'verbose_name': 'Ana səhifə media',
                'verbose_name_plural': 'Ana səhifə media',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
