# Generated by Django 6.0.7 on 2026-07-21 18:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_page_headers_and_remove_about_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeheromedia',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Ana səhifə media', 'verbose_name_plural': 'Ana səhifə — şəkil və videolar'},
        ),
        migrations.AlterModelOptions(
            name='pageheader',
            options={'ordering': ('page',), 'verbose_name': 'Səhifə banneri', 'verbose_name_plural': 'Səhifə bannerləri'},
        ),
        migrations.AlterField(
            model_name='homeheromedia',
            name='header',
            field=models.ForeignKey(limit_choices_to={'page': 'home'}, on_delete=django.db.models.deletion.CASCADE, related_name='home_media', to='core.pageheader', verbose_name='Ana səhifə banneri'),
        ),
        migrations.AlterField(
            model_name='homeheromedia',
            name='image',
            field=models.ImageField(blank=True, help_text='Tip «Şəkil» olduqda mütləq yükləyin. Fayl avtomatik sıxılır.', null=True, upload_to='images/page_headers/home/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='homeheromedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Şəkil'), ('video', 'Video')], help_text='Bu sətir şəkil, yoxsa video olacaq?', max_length=16, verbose_name='Tip'),
        ),
        migrations.AlterField(
            model_name='homeheromedia',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Özünüz seçin: kiçik rəqəm əvvəl başlayır (0 = birinci slayd).', verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='homeheromedia',
            name='video',
            field=models.FileField(blank=True, help_text='Tip «Video» olduqda mütləq yükləyin (məsələn mp4, webm).', null=True, upload_to='videos/page_headers/home/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp4', 'webm', 'mov', 'ogg', 'mkv'), message='İcazə verilən formatlar: mp4, webm, mov, ogg, mkv.')], verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='pageheader',
            name='image',
            field=models.ImageField(blank=True, help_text='Ana səhifədən başqa səhifələrin banner fon şəkli. Ana səhifə seçildikdə bu sahə lazım deyil — şəkil və videoları aşağıdakı «Ana səhifə — şəkil və videolar» siyahısından əlavə edin.', null=True, upload_to='images/page_headers/', verbose_name='Banner şəkli'),
        ),
        migrations.AlterField(
            model_name='pageheader',
            name='motto_az',
            field=models.TextField(blank=True, help_text='Bannerin altındakı qısa şüar (HTML).', validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Deviz (AZ)'),
        ),
        migrations.AlterField(
            model_name='pageheader',
            name='page',
            field=models.CharField(choices=[('home', 'Ana səhifə'), ('about', 'Haqqımızda'), ('services', 'Xidmətlər'), ('portfolio', 'Portfolio'), ('training', 'Təlimlər'), ('blog', 'Bloq'), ('contact', 'Əlaqə'), ('privacy', 'Məxfilik siyasəti'), ('terms', 'İstifadə şərtləri')], help_text='Hansı səhifənin banneri. Hər səhifə üçün yalnız bir qeyd ola bilər.', max_length=32, unique=True, verbose_name='Səhifə'),
        ),
    ]
