# Generated by Django 6.0.7 on 2026-07-21 19:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_about_mezmun_birlesdir'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.CharField(max_length=120, verbose_name='Ad (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ad (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ad (RU)')),
                ('slug', models.SlugField(blank=True, help_text='Avtomatik name_az-dan yaranır. Boş buraxın.', max_length=140, unique=True, verbose_name='Slug')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk. Kiçik rəqəm əvvəl göstərilir.', verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, help_text='Söndürsəniz kateqoriya və xidmətləri filterdə gizlənə bilər.', verbose_name='Aktiv?')),
            ],
            options={
                'verbose_name': 'Xidmət kateqoriyası',
                'verbose_name_plural': 'Xidmət kateqoriyaları',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.CharField(max_length=160, verbose_name='Ad (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='Ad (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=160, null=True, verbose_name='Ad (RU)')),
                ('slug', models.SlugField(blank=True, help_text='Avtomatik name_az-dan yaranır. Boş buraxın.', max_length=180, unique=True, verbose_name='Slug')),
                ('card_text_az', models.TextField(help_text='Yalnız siyahı/karusel kartında görünür — detail səhifədə yox.', verbose_name='Kart mətni (AZ)')),
                ('card_text_en', models.TextField(blank=True, null=True, verbose_name='Kart mətni (EN)')),
                ('card_text_ru', models.TextField(blank=True, null=True, verbose_name='Kart mətni (RU)')),
                ('description_az', models.TextField(help_text='Detail səhifənin böyük mətni (CKEditor).', validators=[django.core.validators.MaxLengthValidator(12000)], verbose_name='Təsvir (AZ)')),
                ('description_en', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(12000)], verbose_name='Təsvir (EN)')),
                ('description_ru', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(12000)], verbose_name='Təsvir (RU)')),
                ('image', models.ImageField(help_text='Kart və siyahıda görünən şəkil. Yükləyəndə avtomatik sıxılır.', upload_to='images/services/', verbose_name='Kart şəkli')),
                ('video', models.FileField(blank=True, help_text='Detail səhifədə play düyməsi ilə açılan video (optional). Poster yoxdur — brauzer ilk kadra düşəcək.', null=True, upload_to='videos/services/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp4', 'webm', 'mov', 'ogg', 'mkv'), message='İcazə verilən formatlar: mp4, webm, mov, ogg, mkv.')], verbose_name='Tanıtım videosu')),
                ('is_active', models.BooleanField(default=True, help_text='Söndürsəniz saytda görünməz.', verbose_name='Aktiv?')),
                ('on_main_page', models.BooleanField(default=False, help_text='Ana səhifə xidmət karuselində göstərilsin.', verbose_name='Ana səhifədə?')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk. Kiçik rəqəm əvvəl göstərilir.', verbose_name='Sıra')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='core.servicecategory', verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Xidmət',
                'verbose_name_plural': 'Xidmətlər',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ServiceGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='İş prosesindən kadr. Yükləyəndə avtomatik sıxılır. Front-da heç bir şəkil yoxdursa bu section gizlədiləcək.', upload_to='images/services/gallery/', verbose_name='Şəkil')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk. Kiçik rəqəm əvvəl göstərilir.', verbose_name='Sıra')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.service', verbose_name='Xidmət')),
            ],
            options={
                'verbose_name': 'İş prosesindən kadr',
                'verbose_name_plural': 'İş prosesindən kadrlar',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ServiceIncludeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_az', models.CharField(max_length=255, verbose_name='Mətn (AZ)')),
                ('text_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mətn (EN)')),
                ('text_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mətn (RU)')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk. Kiçik rəqəm əvvəl göstərilir.', verbose_name='Sıra')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='include_items', to='core.service', verbose_name='Xidmət')),
            ],
            options={
                'verbose_name': 'Xidmətə daxildir',
                'verbose_name_plural': 'Xidmətə daxildir',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ServiceWhyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_az', models.CharField(max_length=255, verbose_name='Mətn (AZ)')),
                ('text_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mətn (EN)')),
                ('text_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mətn (RU)')),
                ('icon', models.CharField(blank=True, choices=[('lucide:briefcase', 'Agentlik / iş'), ('lucide:graduation-cap', 'Academy / təlim'), ('lucide:sparkles', 'Missiya / dəyərlər'), ('lucide:target', 'Hədəf'), ('lucide:users', 'Komanda'), ('lucide:lightbulb', 'İdeya'), ('lucide:rocket', 'Artım / start'), ('lucide:heart', 'Dəyərlər'), ('lucide:award', 'Mükafat / keyfiyyət'), ('lucide:globe', 'Qlobal / region'), ('lucide:code-2', 'Texnologiya'), ('lucide:palette', 'Dizayn / brend'), ('lucide:check-circle', 'Keyfiyyət / təsdiq'), ('lucide:clock', 'Vaxt / sürət'), ('lucide:shield-check', 'Etibar / təhlükəsizlik'), ('lucide:trending-up', 'Artım')], help_text='Iconify (Lucide) ikonu.', max_length=64, null=True, verbose_name='İkon')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk. Kiçik rəqəm əvvəl göstərilir.', verbose_name='Sıra')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_items', to='core.service', verbose_name='Xidmət')),
            ],
            options={
                'verbose_name': 'Niyə bu xidmət?',
                'verbose_name_plural': 'Niyə bu xidmət?',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
