# Generated by Django 6.0.7 on 2026-07-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ('name_az', 'id'), 'verbose_name': 'Xidmət kateqoriyası', 'verbose_name_plural': 'Xidmət kateqoriyaları'},
        ),
        migrations.AlterModelOptions(
            name='servicegalleryimage',
            options={'ordering': ('id',), 'verbose_name': 'İş prosesindən kadr', 'verbose_name_plural': 'İş prosesindən kadrlar'},
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='servicegalleryimage',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='Avtomatik name_az-dan yaranır.', max_length=180, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='Avtomatik name_az-dan yaranır.', max_length=140, unique=True, verbose_name='Slug'),
        ),
    ]
