# Generated by Django 6.0.7 on 2026-07-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_service_cleanup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceincludeitem',
            options={'ordering': ('id',), 'verbose_name': 'Xidmətə daxildir', 'verbose_name_plural': 'Xidmətə daxildir'},
        ),
        migrations.RemoveField(
            model_name='serviceincludeitem',
            name='sort_order',
        ),
    ]
