# Generated by Django 6.0.7 on 2026-07-21 19:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_include_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.CharField(max_length=160, verbose_name='Ad (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='Ad (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=160, null=True, verbose_name='Ad (RU)')),
                ('slug', models.SlugField(blank=True, help_text='Avtomatik name_az-dan yaranır.', max_length=180, unique=True, verbose_name='Slug')),
                ('subtitle_az', models.CharField(help_text='Detail səhifədəki qısa alt başlıq (məs: Brend kimliyi, veb…).', max_length=255, verbose_name='Alt başlıq (AZ)')),
                ('subtitle_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt başlıq (EN)')),
                ('subtitle_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt başlıq (RU)')),
                ('description_az', models.TextField(help_text='Layihə haqqında mətn (CKEditor).', validators=[django.core.validators.MaxLengthValidator(12000)], verbose_name='Təsvir (AZ)')),
                ('description_en', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(12000)], verbose_name='Təsvir (EN)')),
                ('description_ru', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(12000)], verbose_name='Təsvir (RU)')),
                ('cover_image', models.ImageField(help_text='Portfolio kartında görünən şəkil. Yükləyəndə avtomatik sıxılır.', upload_to='images/projects/', verbose_name='Kart şəkli')),
                ('video', models.FileField(blank=True, help_text='Detail səhifədə play düyməsi ilə açılan video (optional). Poster yoxdur — brauzer ilk kadra düşəcək.', null=True, upload_to='videos/projects/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp4', 'webm', 'mov', 'ogg', 'mkv'), message='İcazə verilən formatlar: mp4, webm, mov, ogg, mkv.')], verbose_name='Tanıtım videosu')),
                ('url_web', models.URLField(blank=True, help_text='Dolu olsa kartda veb ikonu görünür.', max_length=500, verbose_name='Veb sayt')),
                ('url_instagram', models.URLField(blank=True, max_length=500, verbose_name='Instagram')),
                ('url_facebook', models.URLField(blank=True, max_length=500, verbose_name='Facebook')),
                ('url_tiktok', models.URLField(blank=True, max_length=500, verbose_name='TikTok')),
                ('url_linkedin', models.URLField(blank=True, max_length=500, verbose_name='LinkedIn')),
                ('url_youtube', models.URLField(blank=True, max_length=500, verbose_name='YouTube')),
                ('is_active', models.BooleanField(default=True, help_text='Söndürsəniz saytda görünməz.', verbose_name='Aktiv?')),
                ('on_main_page', models.BooleanField(default=False, help_text='Ana səhifə «Gördüyümüz işlər» blokunda göstərilsin.', verbose_name='Ana səhifədə?')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk. Kiçik rəqəm əvvəl göstərilir.', verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Layihə',
                'verbose_name_plural': 'Layihələr',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Qalereya şəkli. Yükləyəndə avtomatik sıxılır.', upload_to='images/projects/gallery/', verbose_name='Şəkil')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk. Kiçik rəqəm əvvəl göstərilir.', verbose_name='Sıra')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.project', verbose_name='Layihə')),
            ],
            options={
                'verbose_name': 'Qalereya şəkli',
                'verbose_name_plural': 'Qalereya şəkilləri',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectServiceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.CharField(max_length=120, verbose_name='Ad (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ad (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ad (RU)')),
                ('icon', models.CharField(blank=True, choices=[('lucide:briefcase', 'Agentlik / iş'), ('lucide:graduation-cap', 'Academy / təlim'), ('lucide:sparkles', 'Missiya / dəyərlər'), ('lucide:target', 'Hədəf'), ('lucide:users', 'Komanda'), ('lucide:lightbulb', 'İdeya'), ('lucide:rocket', 'Artım / start'), ('lucide:heart', 'Dəyərlər'), ('lucide:award', 'Mükafat / keyfiyyət'), ('lucide:globe', 'Qlobal / region'), ('lucide:code-2', 'Texnologiya'), ('lucide:palette', 'Dizayn / brend'), ('lucide:check-circle', 'Keyfiyyət / təsdiq'), ('lucide:clock', 'Vaxt / sürət'), ('lucide:shield-check', 'Etibar / təhlükəsizlik'), ('lucide:trending-up', 'Artım'), ('lucide:monitor', 'Web / monitor'), ('lucide:smartphone', 'Mobil'), ('lucide:camera', 'Foto / media'), ('lucide:megaphone', 'Marketinq')], help_text='Iconify (Lucide) ikonu — detail tag-lər üçün.', max_length=64, null=True, verbose_name='İkon')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk. Kiçik rəqəm əvvəl göstərilir.', verbose_name='Sıra')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tags', to='core.project', verbose_name='Layihə')),
            ],
            options={
                'verbose_name': 'Xidmət teqi',
                'verbose_name_plural': 'Xidmət teqləri',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectWhatWeDid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_az', models.CharField(max_length=255, verbose_name='Mətn (AZ)')),
                ('text_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mətn (EN)')),
                ('text_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mətn (RU)')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk. Kiçik rəqəm əvvəl göstərilir.', verbose_name='Sıra')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='what_we_did', to='core.project', verbose_name='Layihə')),
            ],
            options={
                'verbose_name': 'Nələr etdik',
                'verbose_name_plural': 'Layihədə nələr etdik',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
