# Generated by Django 6.0.7 on 2026-07-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_project_projectgalleryimage_projectservicetag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('id',), 'verbose_name': 'Layihə', 'verbose_name_plural': 'Layihələr'},
        ),
        migrations.AlterModelOptions(
            name='projectgalleryimage',
            options={'ordering': ('id',), 'verbose_name': 'Qalereya şəkli', 'verbose_name_plural': 'Qalereya şəkilləri'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='projectgalleryimage',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='projectgalleryimage',
            name='is_cover',
            field=models.BooleanField(default=False, help_text='İşarələsəniz bu şəkil portfolio kartında görünəcək. Bir layihədə yalnız biri.', verbose_name='Kart şəkli?'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='icon',
            field=models.CharField(blank=True, choices=[('lucide:briefcase', 'Agentlik / iş'), ('lucide:graduation-cap', 'Academy / təlim'), ('lucide:sparkles', 'Missiya / dəyərlər'), ('lucide:target', 'Hədəf'), ('lucide:users', 'Komanda'), ('lucide:lightbulb', 'İdeya'), ('lucide:rocket', 'Artım / start'), ('lucide:heart', 'Dəyərlər'), ('lucide:award', 'Mükafat / keyfiyyət'), ('lucide:globe', 'Qlobal / region'), ('lucide:code-2', 'Texnologiya'), ('lucide:palette', 'Dizayn / brend')], help_text='Hansı ikon seçilsə, saytda həmin ikon görünəcək.', max_length=64, null=True, verbose_name='İkon'),
        ),
        migrations.AlterField(
            model_name='projectservicetag',
            name='icon',
            field=models.CharField(blank=True, choices=[('lucide:briefcase', 'Agentlik / iş'), ('lucide:graduation-cap', 'Academy / təlim'), ('lucide:sparkles', 'Missiya / dəyərlər'), ('lucide:target', 'Hədəf'), ('lucide:users', 'Komanda'), ('lucide:lightbulb', 'İdeya'), ('lucide:rocket', 'Artım / start'), ('lucide:heart', 'Dəyərlər'), ('lucide:award', 'Mükafat / keyfiyyət'), ('lucide:globe', 'Qlobal / region'), ('lucide:code-2', 'Texnologiya'), ('lucide:palette', 'Dizayn / brend'), ('lucide:check-circle', 'Keyfiyyət / təsdiq'), ('lucide:clock', 'Vaxt / sürət'), ('lucide:shield-check', 'Etibar / təhlükəsizlik'), ('lucide:trending-up', 'Artım'), ('lucide:monitor', 'Web / monitor'), ('lucide:smartphone', 'Mobil'), ('lucide:camera', 'Foto / media'), ('lucide:megaphone', 'Marketinq')], help_text='Hansı ikon seçilsə, saytda həmin ikon görünəcək.', max_length=64, null=True, verbose_name='İkon'),
        ),
        migrations.AlterField(
            model_name='servicewhyitem',
            name='icon',
            field=models.CharField(blank=True, choices=[('lucide:briefcase', 'Agentlik / iş'), ('lucide:graduation-cap', 'Academy / təlim'), ('lucide:sparkles', 'Missiya / dəyərlər'), ('lucide:target', 'Hədəf'), ('lucide:users', 'Komanda'), ('lucide:lightbulb', 'İdeya'), ('lucide:rocket', 'Artım / start'), ('lucide:heart', 'Dəyərlər'), ('lucide:award', 'Mükafat / keyfiyyət'), ('lucide:globe', 'Qlobal / region'), ('lucide:code-2', 'Texnologiya'), ('lucide:palette', 'Dizayn / brend'), ('lucide:check-circle', 'Keyfiyyət / təsdiq'), ('lucide:clock', 'Vaxt / sürət'), ('lucide:shield-check', 'Etibar / təhlükəsizlik'), ('lucide:trending-up', 'Artım')], help_text='Hansı ikon seçilsə, saytda həmin ikon görünəcək.', max_length=64, null=True, verbose_name='İkon'),
        ),
        migrations.AlterField(
            model_name='statisticitem',
            name='icon',
            field=models.CharField(blank=True, choices=[('lucide:calendar-check', 'Təcrübə / illər'), ('lucide:users', 'Müştərilər / komanda'), ('lucide:briefcase', 'Layihələr'), ('lucide:award', 'Mükafat'), ('lucide:trending-up', 'Artım'), ('lucide:globe', 'Ölkə / region'), ('lucide:thumbs-up', 'Məmnuniyyət'), ('lucide:star', 'Reytinq'), ('lucide:handshake', 'Tərəfdaşlıq'), ('lucide:rocket', 'Start / sürət'), ('lucide:graduation-cap', 'Təlim / Academy'), ('lucide:heart', 'Sevgi / loyallıq')], help_text='Hansı ikon seçilsə, saytda həmin ikon görünəcək.', max_length=64, null=True, verbose_name='İkon'),
        ),
    ]
