# Generated by Django 6.0.7 on 2026-07-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectservicetag',
            options={'ordering': ('id',), 'verbose_name': 'Xidmət teqi', 'verbose_name_plural': 'Xidmət teqləri'},
        ),
        migrations.RemoveField(
            model_name='projectservicetag',
            name='sort_order',
        ),
    ]
