# Generated by Django 6.0.7 on 2026-07-21 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_projectservicetag_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.CharField(max_length=160, verbose_name='Ad (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='Ad (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=160, null=True, verbose_name='Ad (RU)')),
                ('slug', models.SlugField(blank=True, help_text='Avtomatik name_az-dan yaranır.', max_length=180, unique=True, verbose_name='Slug')),
                ('description_az', models.TextField(help_text='Paket adının altındakı qısa mətn.', verbose_name='Təsvir (AZ)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Təsvir (EN)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Təsvir (RU)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiymət')),
                ('currency', models.CharField(choices=[('AZN', 'AZN'), ('USD', 'USD'), ('EUR', 'EUR')], default='AZN', max_length=3, verbose_name='Valyuta')),
                ('price_from', models.BooleanField(default=False, help_text='İşarələsəniz qiymətə «-dan/-dən» əlavə olunur (məs: 565-dən).', verbose_name='Qiymətə dan/dən?')),
                ('is_active', models.BooleanField(default=True, help_text='Söndürsəniz heç yerdə görünməz.', verbose_name='Aktiv?')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk. Kiçik rəqəm əvvəl göstərilir.', verbose_name='Sıra')),
                ('show_on_home', models.BooleanField(default=False, help_text='Ana səhifə «Xüsusi paketlər» blokunda göstərilsin.', verbose_name='Ana səhifədə?')),
                ('show_on_services', models.BooleanField(default=True, help_text='Adətən True — xidmətlər səhifəsində bütün aktiv paketlər.', verbose_name='Xidmətlər səhifəsində?')),
                ('show_in_footer', models.BooleanField(default=False, help_text='Footer Xidmətlər/Paketlər siyahısında.', verbose_name='Footer-də?')),
            ],
            options={
                'verbose_name': 'Paket',
                'verbose_name_plural': 'Paketlər',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_az', models.CharField(max_length=255, verbose_name='Mətn (AZ)')),
                ('text_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mətn (EN)')),
                ('text_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mətn (RU)')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk. Kiçik rəqəm əvvəl göstərilir.', verbose_name='Sıra')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.package', verbose_name='Paket')),
            ],
            options={
                'verbose_name': 'Nələr daxildir',
                'verbose_name_plural': 'Nələr daxildir',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
