# Generated by Django 6.0.7 on 2026-07-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_packages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='show_on_services',
        ),
        migrations.AlterField(
            model_name='package',
            name='price_from',
            field=models.BooleanField(default=False, help_text='İşarələsəniz qiymətə «-dan/-dən» (EN: from, RU: от) avtomatik əlavə olunur — dilə və AZ sait ahənginə görə.', verbose_name='Qiymətə dan/dən?'),
        ),
    ]
