# Generated by Django 6.0.7 on 2026-07-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_package_show_on_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price_from',
            field=models.BooleanField(default=False, help_text='İşarələsəniz qiymətə «-dan/-dən» əlavə olunur (məs: 565-dən).', verbose_name='Qiymətə dan/dən?'),
        ),
    ]
