# Generated by Django 6.0.7 on 2026-07-21 20:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_package_price_from_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.CharField(max_length=120, verbose_name='Ad (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ad (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ad (RU)')),
                ('slug', models.SlugField(blank=True, help_text='Avtomatik name_az-dan yaranır.', max_length=140, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, help_text='Söndürsəniz filterdə görünməz.', verbose_name='Aktiv?')),
            ],
            options={
                'verbose_name': 'Bloq kateqoriyası',
                'verbose_name_plural': 'Bloq kateqoriyaları',
                'ordering': ('name_az', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.CharField(max_length=200, verbose_name='Başlıq (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq (RU)')),
                ('slug', models.SlugField(blank=True, help_text='Avtomatik name_az-dan yaranır.', max_length=220, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(help_text='Kart və detail-də görünən şəkil. Yükləyəndə avtomatik sıxılır.', upload_to='images/blogs/', verbose_name='Cover şəkil')),
                ('description_az', models.TextField(help_text='Bloq məzmunu (CKEditor).', validators=[django.core.validators.MaxLengthValidator(12000)], verbose_name='Məzmun (AZ)')),
                ('description_en', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(12000)], verbose_name='Məzmun (EN)')),
                ('description_ru', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(12000)], verbose_name='Məzmun (RU)')),
                ('date', models.DateField(verbose_name='Tarix')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Avtomatik — detail səhifədə artacaq. Əl ilə dəyişməyin.', verbose_name='Baxış sayı')),
                ('is_active', models.BooleanField(default=True, help_text='Söndürsəniz saytda görünməz.', verbose_name='Aktiv?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='core.blogcategory', verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Bloq',
                'verbose_name_plural': 'Bloqlar',
                'ordering': ('-date', '-id'),
            },
        ),
    ]
