# Generated by Django 6.0.7 on 2026-07-21 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='is_active',
        ),
    ]
