# Generated by Django 6.0.7 on 2026-07-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_blogcategory_remove_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_az', models.CharField(help_text='Göstərilən mətn. Məs: Əhməd Rəcəbli 49B, Bakı', max_length=255, verbose_name='Ünvan (AZ)')),
                ('address_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ünvan (EN)')),
                ('address_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ünvan (RU)')),
                ('address_map_url', models.URLField(blank=True, help_text='Optional Google Maps link / axtarış URL.', max_length=500, null=True, verbose_name='Xəritə linki')),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps iframe src (ofis xəritəsi).', max_length=1000, null=True, verbose_name='Xəritə embed URL')),
                ('whatsapp_number', models.CharField(help_text='Göstəriş formatı. Məs: +994 50 123 45 67', max_length=40, verbose_name='WhatsApp nömrəsi')),
                ('whatsapp_link', models.URLField(blank=True, help_text='Boşdursa wa.me linki nömrədən avtomatik qurulur.', max_length=255, null=True, verbose_name='WhatsApp linki')),
                ('email', models.EmailField(help_text='Məs: info@digiboom.az', max_length=254, verbose_name='E-poçt')),
                ('phone', models.CharField(blank=True, help_text='Optional — footer üçün. Contact siyahısında yoxdursa boş saxlayın.', max_length=40, null=True, verbose_name='Telefon')),
                ('facebook_handle', models.CharField(blank=True, help_text='Məs: /digiboom', max_length=80, null=True, verbose_name='Facebook handle')),
                ('facebook_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook URL')),
                ('instagram_handle', models.CharField(blank=True, help_text='Məs: @digiboom', max_length=80, null=True, verbose_name='Instagram handle')),
                ('instagram_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram URL')),
                ('tiktok_handle', models.CharField(blank=True, help_text='Məs: @digiboom', max_length=80, null=True, verbose_name='TikTok handle')),
                ('tiktok_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='TikTok URL')),
                ('linkedin_handle', models.CharField(blank=True, help_text='Məs: Digiboom', max_length=80, null=True, verbose_name='LinkedIn handle')),
                ('linkedin_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='LinkedIn URL')),
                ('youtube_handle', models.CharField(blank=True, help_text='Məs: @digiboom', max_length=80, null=True, verbose_name='YouTube handle')),
                ('youtube_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='YouTube URL')),
            ],
            options={
                'verbose_name': 'Əlaqə məlumatları',
                'verbose_name_plural': 'Əlaqə məlumatları',
            },
        ),
    ]
