# Generated by Django 6.0.7 on 2026-07-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address_map_url',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='facebook_handle',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='instagram_handle',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='linkedin_handle',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='map_embed_url',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tiktok_handle',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='youtube_handle',
        ),
        migrations.AddField(
            model_name='contact',
            name='map_url',
            field=models.URLField(blank=True, help_text='Google Maps linki — həm ofis xəritəsi, həm ünvana klik üçün eyni link.', max_length=1000, null=True, verbose_name='Xəritə linki'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Profil linkini yapışdırın.', max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Profil linkini yapışdırın.', max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Profil linkini yapışdırın.', max_length=255, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='Profil linkini yapışdırın.', max_length=255, null=True, verbose_name='TikTok'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Profil linkini yapışdırın.', max_length=255, null=True, verbose_name='YouTube'),
        ),
    ]
