# Generated by Django 6.0.7 on 2026-07-21 20:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_contact_simplify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ad, Soyad')),
                ('category_type', models.CharField(choices=[('service', 'Xidmət'), ('training', 'Təlim'), ('consultation', 'Konsultasiya'), ('other', 'Digər')], help_text='Sayt modal qrupları: Xidmət / Təlim / Konsultasiya / Digər.', max_length=20, verbose_name='Kateqoriya tipi')),
                ('category_label', models.CharField(help_text='Seçilmiş alt bəndin adı (snapshot) — siyahı/filterdə faydalı. Təlim üçün Training FK gələnə qədər əsas saxlama yeri.', max_length=200, verbose_name='Seçilmiş bənd')),
                ('rating', models.PositiveSmallIntegerField(help_text='1–5 ulduz.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Reytinq')),
                ('message', models.TextField(help_text='Rəy mətni.', verbose_name='Rəy')),
                ('image', models.ImageField(blank=True, help_text='İstəyə bağlı. Yükləyəndə avtomatik sıxılır.', null=True, upload_to='images/reviews/', verbose_name='Şəkil')),
                ('is_active', models.BooleanField(default=False, help_text='Yalnız işarələnənlər saytda görünür (moderasiya).', verbose_name='Saytda göstərilsin?')),
                ('is_read', models.BooleanField(default=False, help_text='Admin paneldə oxunub kimi işarələmək üçün (Averta).', verbose_name='Oxunub?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yazılma vaxtı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə')),
                ('service', models.ForeignKey(blank=True, help_text='category_type=service olanda doldurulur (sonra sayt POST-u).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.service', verbose_name='Xidmət')),
            ],
            options={
                'verbose_name': 'Rəy',
                'verbose_name_plural': 'Rəylər',
                'ordering': ('-created_at',),
            },
        ),
    ]
