# Generated by Django 6.0.7 on 2026-07-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tiktok_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='TikTok'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whatsapp_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='WhatsApp linki'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='YouTube'),
        ),
    ]
