# Generated by Django 6.0.7 on 2026-07-21 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_contact_clear_help'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='whatsapp_link',
        ),
    ]
