# Generated by Django 6.0.7 on 2026-07-21 20:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_whatsapp_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='category_label',
            field=models.CharField(blank=True, default='', help_text='Təlim adı və ya digər seçim. Xidmətdə boş qala bilər (xidmət adından götürülür).', max_length=200, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='review',
            name='category_type',
            field=models.CharField(choices=[('service', 'Xidmət'), ('training', 'Təlim'), ('consultation', 'Konsultasiya'), ('other', 'Digər')], max_length=20, verbose_name='Tip'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/reviews/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Saytda göstərilsin?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Oxunub?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(verbose_name='Rəy'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Reytinq'),
        ),
        migrations.AlterField(
            model_name='review',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.service', verbose_name='Xidmət'),
        ),
    ]
