# Generated by Django 6.0.7 on 2026-07-21 20:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_review_category_simplify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.CharField(max_length=160, verbose_name='Ad (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='Ad (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=160, null=True, verbose_name='Ad (RU)')),
                ('slug', models.SlugField(blank=True, help_text='Avtomatik name_az-dan yaranır.', max_length=180, unique=True, verbose_name='Slug')),
                ('card_text_az', models.TextField(help_text='Yalnız siyahı/kartında görünür — detail səhifədə yox.', verbose_name='Kart mətni (AZ)')),
                ('card_text_en', models.TextField(blank=True, null=True, verbose_name='Kart mətni (EN)')),
                ('card_text_ru', models.TextField(blank=True, null=True, verbose_name='Kart mətni (RU)')),
                ('description_az', models.TextField(help_text='Detail lead / təsvir (CKEditor).', validators=[django.core.validators.MaxLengthValidator(12000)], verbose_name='Təsvir (AZ)')),
                ('description_en', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(12000)], verbose_name='Təsvir (EN)')),
                ('description_ru', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(12000)], verbose_name='Təsvir (RU)')),
                ('image', models.ImageField(help_text='Kart və cover şəkil. Yükləyəndə avtomatik sıxılır.', upload_to='images/trainings/', verbose_name='Kart şəkli')),
                ('video', models.FileField(blank=True, help_text='Detail səhifədə play düyməsi ilə açılan video (optional).', null=True, upload_to='videos/trainings/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp4', 'webm', 'mov', 'ogg', 'mkv'), message='İcazə verilən formatlar: mp4, webm, mov, ogg, mkv.')], verbose_name='Tanıtım videosu')),
                ('video_poster', models.ImageField(blank=True, help_text='Detail player üçün poster (optional). Yükləyəndə avtomatik sıxılır.', null=True, upload_to='images/trainings/posters/', verbose_name='Video poster')),
                ('duration_hours', models.PositiveIntegerField(verbose_name='Müddət (saat)')),
                ('lesson_count', models.PositiveIntegerField(verbose_name='Dərs sayı')),
                ('level', models.CharField(choices=[('beginner', 'Başlanğıc'), ('intermediate', 'Orta'), ('advanced', 'İrəli')], max_length=20, verbose_name='Səviyyə')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiymət (AZN)')),
                ('is_popular', models.BooleanField(default=False, help_text='Spotlight / «Ən populyar» işarəsi.', verbose_name='Ən populyar?')),
                ('is_active', models.BooleanField(default=True, help_text='Söndürsəniz saytda görünməz.', verbose_name='Aktiv?')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk. Kiçik rəqəm əvvəl göstərilir.', verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Təlim',
                'verbose_name_plural': 'Təlimlər',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.CharField(max_length=120, verbose_name='Ad (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ad (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ad (RU)')),
                ('slug', models.SlugField(blank=True, help_text='Avtomatik name_az-dan yaranır (məs: smm, seo).', max_length=140, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Təlim kateqoriyası',
                'verbose_name_plural': 'Təlim kateqoriyaları',
                'ordering': ('name_az',),
            },
        ),
        migrations.AlterField(
            model_name='review',
            name='category_label',
            field=models.CharField(blank=True, default='', help_text='Saytdan gələn seçim: Digər, xidmət və ya təlim adı.', max_length=200, verbose_name='Kateqoriya'),
        ),
        migrations.AddField(
            model_name='review',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.training', verbose_name='Təlim'),
        ),
        migrations.AddField(
            model_name='training',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='core.trainingcategory', verbose_name='Kateqoriya'),
        ),
        migrations.CreateModel(
            name='TrainingCurriculumItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_az', models.CharField(max_length=200, verbose_name='Başlıq (AZ)')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq (EN)')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq (RU)')),
                ('text_az', models.CharField(max_length=255, verbose_name='İzah (AZ)')),
                ('text_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='İzah (EN)')),
                ('text_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='İzah (RU)')),
                ('video', models.FileField(upload_to='videos/trainings/curriculum/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp4', 'webm', 'mov', 'ogg', 'mkv'), message='İcazə verilən formatlar: mp4, webm, mov, ogg, mkv.')], verbose_name='Preview video')),
                ('thumb', models.ImageField(blank=True, help_text='Siyahı thumbnail (optional). Yükləyəndə avtomatik sıxılır.', null=True, upload_to='images/trainings/curriculum/', verbose_name='Thumbnail')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk. Kiçik rəqəm əvvəl göstərilir.', verbose_name='Sıra')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_items', to='core.training', verbose_name='Təlim')),
            ],
            options={
                'verbose_name': 'Kurs məzmunu',
                'verbose_name_plural': 'Kurs məzmunu — icmal videoları',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TrainingGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Təlimdən kadr. Yükləyəndə avtomatik sıxılır.', upload_to='images/trainings/gallery/', verbose_name='Şəkil')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.training', verbose_name='Təlim')),
            ],
            options={
                'verbose_name': 'Təlimdən kadr',
                'verbose_name_plural': 'Təlimdən kadrlar',
                'ordering': ('id',),
            },
        ),
    ]
