# Generated by Django 6.0.7 on 2026-07-21 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_trainings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_az', models.CharField(max_length=500, verbose_name='Sual (AZ)')),
                ('question_en', models.CharField(blank=True, default='', max_length=500, verbose_name='Sual (EN)')),
                ('question_ru', models.CharField(blank=True, default='', max_length=500, verbose_name='Sual (RU)')),
                ('answer_az', models.TextField(blank=True, default='', help_text='Sadə FAQ üçün doldurun. Nested (alt suallar) varsa boş saxlaya bilərsiniz. Alt bənd əlavə etsəniz nested olur; əlavə etməsəniz answer yazın.', verbose_name='Cavab (AZ)')),
                ('answer_en', models.TextField(blank=True, default='', help_text='Sadə FAQ üçün doldurun. Nested (alt suallar) varsa boş saxlaya bilərsiniz.', verbose_name='Cavab (EN)')),
                ('answer_ru', models.TextField(blank=True, default='', help_text='Sadə FAQ üçün doldurun. Nested (alt suallar) varsa boş saxlaya bilərsiniz.', verbose_name='Cavab (RU)')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk. Kiçik rəqəm əvvəl göstərilir.', verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Saytda göstərilsin?')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ-lar',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FAQSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_az', models.CharField(help_text='Alt accordion trigger, məs. «Rəqəmsal marketinq».', max_length=500, verbose_name='Başlıq (AZ)')),
                ('title_en', models.CharField(blank=True, default='', max_length=500, verbose_name='Başlıq (EN)')),
                ('title_ru', models.CharField(blank=True, default='', max_length=500, verbose_name='Başlıq (RU)')),
                ('answer_az', models.TextField(verbose_name='Cavab (AZ)')),
                ('answer_en', models.TextField(blank=True, default='', verbose_name='Cavab (EN)')),
                ('answer_ru', models.TextField(blank=True, default='', verbose_name='Cavab (RU)')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk. Kiçik rəqəm əvvəl göstərilir.', verbose_name='Sıra')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='core.faq', verbose_name='FAQ')),
            ],
            options={
                'verbose_name': 'Alt sual / cavab',
                'verbose_name_plural': 'Alt suallar / cavablar',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
