# Generated by Django 6.0.7 on 2026-07-21 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingcurriculumitem',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'İcmal', 'verbose_name_plural': 'Kurs məzmunu — icmal'},
        ),
        migrations.RemoveField(
            model_name='training',
            name='card_text_az',
        ),
        migrations.RemoveField(
            model_name='training',
            name='card_text_en',
        ),
        migrations.RemoveField(
            model_name='training',
            name='card_text_ru',
        ),
        migrations.RemoveField(
            model_name='training',
            name='image',
        ),
        migrations.RemoveField(
            model_name='training',
            name='video',
        ),
        migrations.RemoveField(
            model_name='training',
            name='video_poster',
        ),
        migrations.RemoveField(
            model_name='trainingcurriculumitem',
            name='thumb',
        ),
        migrations.AddField(
            model_name='trainingcurriculumitem',
            name='is_promo',
            field=models.BooleanField(default=False, help_text='İşarələsəniz bu video detail-də tanıtım kimi görünəcək. Bir təlimdə yalnız biri.', verbose_name='Tanıtım videosu?'),
        ),
        migrations.AddField(
            model_name='traininggalleryimage',
            name='is_cover',
            field=models.BooleanField(default=False, help_text='İşarələsəniz bu şəkil təlim kartında görünəcək. Bir təlimdə yalnız biri.', verbose_name='Kart şəkli?'),
        ),
        migrations.AlterField(
            model_name='training',
            name='description_az',
            field=models.TextField(help_text='Kart və detail üçün eyni mətn (CKEditor).', validators=[django.core.validators.MaxLengthValidator(12000)], verbose_name='Təsvir (AZ)'),
        ),
        migrations.AlterField(
            model_name='trainingcategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='Avtomatik name_az-dan yaranır.', max_length=140, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='trainingcurriculumitem',
            name='video',
            field=models.FileField(upload_to='videos/trainings/curriculum/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp4', 'webm', 'mov', 'ogg', 'mkv'), message='İcazə verilən formatlar: mp4, webm, mov, ogg, mkv.')], verbose_name='Önizləmə'),
        ),
    ]
