# Generated by Django 6.0.7 on 2026-07-21 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_training_simplify'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Tez-tez verilən sual', 'verbose_name_plural': 'Tez-tez verilən suallar'},
        ),
        migrations.AlterModelOptions(
            name='faqsubitem',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': '2-ci dərəcəli sual və cavab', 'verbose_name_plural': '2-ci dərəcəli suallar və cavablar'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_az',
            field=models.TextField(blank=True, default='', help_text='2-ci dərəcəli suallar əlavə etsəniz bu sahəni boş saxlayın — cavablar alt bəndlərdə yazılır. Alt bənd yoxdursa burada cavab yazın.', verbose_name='Cavab (AZ) — yalnız sadə FAQ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(blank=True, default='', verbose_name='Cavab (EN) — yalnız sadə FAQ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(blank=True, default='', verbose_name='Cavab (RU) — yalnız sadə FAQ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_az',
            field=models.CharField(help_text='Ana accordion — məs. «Digiboom nə şirkətdir?»', max_length=500, verbose_name='1-ci dərəcəli sual (AZ)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_en',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='1-ci dərəcəli sual (EN)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='1-ci dərəcəli sual (RU)'),
        ),
        migrations.AlterField(
            model_name='faqsubitem',
            name='faq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='core.faq', verbose_name='1-ci dərəcəli sual'),
        ),
        migrations.AlterField(
            model_name='faqsubitem',
            name='title_az',
            field=models.CharField(help_text='Məs. «Digiboom SEO olaraq?»', max_length=500, verbose_name='2-ci dərəcəli sual (AZ)'),
        ),
        migrations.AlterField(
            model_name='faqsubitem',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='2-ci dərəcəli sual (EN)'),
        ),
        migrations.AlterField(
            model_name='faqsubitem',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='2-ci dərəcəli sual (RU)'),
        ),
    ]
