# Generated by Django 6.0.7 on 2026-07-21 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_faq_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='description_az',
            field=models.TextField(help_text='Kart və detail üçün eyni mətn.', validators=[django.core.validators.MaxLengthValidator(12000)], verbose_name='Təsvir (AZ)'),
        ),
    ]
