# Generated by Django 6.0.7 on 2026-07-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_training_description_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer_az',
            field=models.TextField(blank=True, default='', help_text='2-ci dərəcəli sual yoxdursa burada yazın. 2-ci dərəcə varsa boş saxlayın — cavablar aşağıdakı cədvəldədir.', verbose_name='Birbaşa cavab (AZ)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(blank=True, default='', verbose_name='Birbaşa cavab (EN)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(blank=True, default='', verbose_name='Birbaşa cavab (RU)'),
        ),
    ]
