# Generated by Django 6.0.7 on 2026-07-21 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_faq_answer_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer_az',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_en',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_ru',
        ),
        migrations.AlterField(
            model_name='faqsubitem',
            name='title_az',
            field=models.CharField(blank=True, default='', help_text='Varsa yazın — məs. «Digiboom SEO olaraq?». Yoxdursa boş saxlayın, yalnız cavab doldurun.', max_length=500, verbose_name='2-ci dərəcəli sual (AZ)'),
        ),
        migrations.CreateModel(
            name='TrainingAccessLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_az', models.CharField(max_length=200, verbose_name='Başlıq (AZ)')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq (EN)')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq (RU)')),
                ('url', models.URLField(help_text='Ödəniş uğurlu olanda müştəriyə göndəriləcək URL.', max_length=500, verbose_name='Link')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk. Kiçik rəqəm əvvəl göndərilir.', verbose_name='Sıra')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_links', to='core.training', verbose_name='Təlim')),
            ],
            options={
                'verbose_name': 'Müştəri linki',
                'verbose_name_plural': 'Ödənişdən sonra göndərilən linklər',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
