# Generated by Django 6.0.7 on 2026-07-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_faq_remove_direct_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingaccesslink',
            options={'ordering': ('id',), 'verbose_name': 'Müştəri linki', 'verbose_name_plural': 'Ödənişdən sonra göndərilən linklər'},
        ),
        migrations.RemoveField(
            model_name='trainingaccesslink',
            name='sort_order',
        ),
    ]
