# Generated by Django 6.0.7 on 2026-07-21 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_access_link_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Ad və soyad')),
                ('phone', models.CharField(max_length=40, verbose_name='Nömrə')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('package_name', models.CharField(blank=True, default='', help_text='Formadan gələn paket adı (snapshot) — paket silinsə belə qalır.', max_length=160, verbose_name='Paket adı')),
                ('message', models.TextField(blank=True, default='', verbose_name='Mesaj')),
                ('is_read', models.BooleanField(default=False, help_text='Sifarişi oxuduqdan sonra işarələyin.', verbose_name='Oxunub?')),
                ('is_customer', models.BooleanField(default=False, help_text='Bu şəxs müştəri olubsa işarələyin.', verbose_name='Müştərimizdir?')),
                ('is_deleted', models.BooleanField(default=False, help_text='Fiziki silmək əvəzinə işarələyin.', verbose_name='Silinib?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.package', verbose_name='Paket')),
            ],
            options={
                'verbose_name': 'Paket sifarişi',
                'verbose_name_plural': 'Paket sifarişləri',
                'ordering': ('-created_at',),
            },
        ),
    ]
