# Generated by Django 6.0.7 on 2026-07-21 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_package_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageorder',
            name='is_customer',
            field=models.BooleanField(default=False, help_text='Bu şəxs müştəri olubsa işarələyin.', verbose_name='Müştəri'),
        ),
        migrations.CreateModel(
            name='TrainingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(blank=True, default='', help_text='Formadan gələn təlim adı (snapshot) — təlim silinsə belə qalır.', max_length=160, verbose_name='Təlim adı')),
                ('full_name', models.CharField(help_text='Form: name="name"', max_length=120, verbose_name='Ad və soyad')),
                ('phone', models.CharField(help_text='Form: name="phone"', max_length=40, verbose_name='Nömrə')),
                ('gmail', models.EmailField(help_text='Form: name="gmail". Yalnız @gmail.com ünvanları qəbul olunur. Digiboom-da digər email istifadə olunmur.', max_length=254, verbose_name='Gmail')),
                ('payment_status', models.CharField(choices=[('pending', 'Gözləyir'), ('paid', 'Ödənib'), ('failed', 'Uğursuz'), ('refunded', 'Geri qaytarılıb')], default='pending', help_text='Gateway sonra bağlanacaq. Test üçün admin-dən dəyişmək olar. Sonra yalnız paid sifarişlər «işlənəcək» siyahıda önə çıxacaq.', max_length=20, verbose_name='Ödəniş statusu')),
                ('payment_id', models.CharField(blank=True, default='', help_text='Gateway transaction id (sonra).', max_length=120, verbose_name='Ödəniş ID')),
                ('provider_ref', models.CharField(blank=True, default='', help_text='Gateway provider referansı (sonra).', max_length=120, verbose_name='Provider ref')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Ödəniş vaxtı')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Ödənilən məbləğ snapshot; Training.price-dan kopyalana bilər.', max_digits=10, null=True, verbose_name='Məbləğ (AZN)')),
                ('is_read', models.BooleanField(default=False, help_text='Sifarişi oxuduqdan sonra işarələyin.', verbose_name='Oxunub?')),
                ('is_customer', models.BooleanField(default=False, help_text='Bu şəxs müştəri olubsa işarələyin.', verbose_name='Müştərimizdir?')),
                ('is_deleted', models.BooleanField(default=False, help_text='Fiziki silmək əvəzinə işarələyin.', verbose_name='Silinib?')),
                ('is_links_sent', models.BooleanField(default=False, help_text='Email göndərmə növbəti fazada bağlanacaq. İndi yalnız Drive linklərini saxlayın; is_links_sent-i əl ilə və ya «Göndərildi kimi işarələ» action ilə qeyd edə bilərsiniz.', verbose_name='Linklər göndərilib?')),
                ('links_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Linklər göndərilmə vaxtı')),
                ('admin_note', models.TextField(blank=True, default='', help_text='Daxili qeyd — müştəriyə göndərilmir.', verbose_name='Admin qeydi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə')),
                ('training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.training', verbose_name='Təlim')),
            ],
            options={
                'verbose_name': 'Təlim sifarişi',
                'verbose_name_plural': 'Təlim sifarişləri',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TrainingOrderDriveLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Məsələn: «Modul 1», «Materiallar».', max_length=160, verbose_name='Başlıq')),
                ('url', models.URLField(help_text='Müştəriyə göndəriləcək Drive / material URL.', max_length=500, verbose_name='Google Drive linki')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_links', to='core.trainingorder', verbose_name='Sifariş')),
            ],
            options={
                'verbose_name': 'Drive linki',
                'verbose_name_plural': 'Drive materialları',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
