# Generated by Django 6.0.7 on 2026-07-21 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_training_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageorder',
            name='is_deleted',
        ),
    ]
