# Generated by Django 6.0.7 on 2026-07-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_package_order_admin_tweaks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingorderdrivelink',
            options={'ordering': ('id',), 'verbose_name': 'Drive linki', 'verbose_name_plural': 'Drive materialları'},
        ),
        migrations.RemoveField(
            model_name='trainingorder',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='trainingorderdrivelink',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='trainingorder',
            name='invoice',
            field=models.CharField(blank=True, default='', help_text='Kapital Bank ödənişindən gələcək qaimə (nömrə / link).', max_length=255, verbose_name='Qaimə'),
        ),
        migrations.AlterField(
            model_name='trainingorder',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Məbləğ (AZN)'),
        ),
        migrations.AlterField(
            model_name='trainingorder',
            name='full_name',
            field=models.CharField(max_length=120, verbose_name='Ad və soyad'),
        ),
        migrations.AlterField(
            model_name='trainingorder',
            name='gmail',
            field=models.EmailField(help_text='Yalnız @gmail.com ünvanı qəbul olunur.', max_length=254, verbose_name='Gmail'),
        ),
        migrations.AlterField(
            model_name='trainingorder',
            name='is_links_sent',
            field=models.BooleanField(default=False, verbose_name='Linklər göndərilib?'),
        ),
        migrations.AlterField(
            model_name='trainingorder',
            name='payment_id',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Ödəniş ID'),
        ),
        migrations.AlterField(
            model_name='trainingorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Gözləyir'), ('paid', 'Ödənib'), ('failed', 'Uğursuz'), ('refunded', 'Geri qaytarılıb')], default='pending', max_length=20, verbose_name='Ödəniş statusu'),
        ),
        migrations.AlterField(
            model_name='trainingorder',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='Nömrə'),
        ),
        migrations.AlterField(
            model_name='trainingorder',
            name='provider_ref',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Provider ref'),
        ),
        migrations.AlterField(
            model_name='trainingorder',
            name='training_name',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Təlim adı'),
        ),
        migrations.AlterField(
            model_name='trainingorderdrivelink',
            name='url',
            field=models.URLField(max_length=500, verbose_name='Google Drive linki'),
        ),
    ]
