# Generated by Django 5.2.16 on 2026-07-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_training_order_admin_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingorder',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='trainingorder',
            name='is_customer',
            field=models.BooleanField(default=False, help_text='Linklər göndərildikdən sonra işarələyin.', verbose_name='Müştərimizdir?'),
        ),
    ]
