# Generated by Django 5.2.16 on 2026-07-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_training_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingorder',
            name='is_added_to_drive',
            field=models.BooleanField(default=False, help_text='Əvvəlcə müştərinin Gmail-ini Google Drive-də paylaşın, sonra bu xananı işarələyin. Əks halda link göndərilməyəcək.', verbose_name='Drive-ə əlavə olunub?'),
        ),
    ]
