# Generated by Django 6.0.7 on 2026-07-22 16:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_training_order_added_to_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageheader',
            name='why_text_az',
            field=models.TextField(blank=True, help_text='Başlığın altındakı qısa izah. Məs: Peşəkar komandadan öyrənin…', validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Niyə biz — mətn (AZ)'),
        ),
        migrations.AddField(
            model_name='pageheader',
            name='why_text_en',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Niyə biz — mətn (EN)'),
        ),
        migrations.AddField(
            model_name='pageheader',
            name='why_text_ru',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Niyə biz — mətn (RU)'),
        ),
        migrations.AddField(
            model_name='pageheader',
            name='why_title_az',
            field=models.CharField(blank=True, help_text='Məsələn: Niyə biz?', max_length=120, verbose_name='Niyə biz — başlıq (AZ)'),
        ),
        migrations.AddField(
            model_name='pageheader',
            name='why_title_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Niyə biz — başlıq (EN)'),
        ),
        migrations.AddField(
            model_name='pageheader',
            name='why_title_ru',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Niyə biz — başlıq (RU)'),
        ),
        migrations.CreateModel(
            name='TrainingStatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Məsələn: 8+, 120+, 500+', max_length=32, verbose_name='Rəqəm / dəyər')),
                ('label_az', models.CharField(help_text='Məsələn: Aktiv kurs, Saat məzmun, Məzun', max_length=120, verbose_name='Alt yazı (AZ)')),
                ('label_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Alt yazı (EN)')),
                ('label_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Alt yazı (RU)')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk. Maksimum 3 statistika.', verbose_name='Sıra')),
                ('header', models.ForeignKey(limit_choices_to={'page': 'training'}, on_delete=django.db.models.deletion.CASCADE, related_name='training_stats', to='core.pageheader', verbose_name='Təlim banneri')),
            ],
            options={
                'verbose_name': 'Təlim — statistika',
                'verbose_name_plural': 'Təlim — statistika (maks. 3)',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TrainingWhyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_az', models.CharField(help_text='Məsələn: Video dərslər və canlı sessiyalar', max_length=200, verbose_name='Səbəb (AZ)')),
                ('text_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Səbəb (EN)')),
                ('text_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Səbəb (RU)')),
                ('icon', models.CharField(blank=True, choices=[('lucide:video', 'Video / dərs'), ('lucide:file-check', 'Sertifikat / təsdiq'), ('lucide:users', 'Komanda / qrup'), ('lucide:infinity', 'Limitsiz giriş'), ('lucide:graduation-cap', 'Academy / təlim'), ('lucide:sparkles', 'Missiya / dəyərlər'), ('lucide:target', 'Hədəf'), ('lucide:lightbulb', 'İdeya'), ('lucide:rocket', 'Artım / start'), ('lucide:award', 'Mükafat / keyfiyyət'), ('lucide:clock', 'Vaxt'), ('lucide:book-open', 'Material / kitab'), ('lucide:headphones', 'Dəstək'), ('lucide:check-circle', 'Keyfiyyət')], help_text='Hansı ikon seçilsə, saytda həmin ikon görünəcək.', max_length=64, null=True, verbose_name='İkon')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='0 = ilk. Kiçik rəqəm əvvəl göstərilir.', verbose_name='Sıra')),
                ('header', models.ForeignKey(limit_choices_to={'page': 'training'}, on_delete=django.db.models.deletion.CASCADE, related_name='training_why_items', to='core.pageheader', verbose_name='Təlim banneri')),
            ],
            options={
                'verbose_name': 'Təlim — səbəb',
                'verbose_name_plural': 'Təlim — səbəblər (Niyə biz?)',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
