# Generated by Django 5.2.16 on 2026-07-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_training_banner_why_stats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingOrderDriveLink',
        ),
    ]
