# Generated by Django 5.2.16 on 2026-07-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_training_order_drive_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageheader',
            name='why_text_az',
        ),
        migrations.RemoveField(
            model_name='pageheader',
            name='why_text_en',
        ),
        migrations.RemoveField(
            model_name='pageheader',
            name='why_text_ru',
        ),
        migrations.AlterField(
            model_name='pageheader',
            name='why_title_az',
            field=models.CharField(blank=True, help_text='Panel başlığı. Məsələn: Niyə biz?', max_length=120, verbose_name='Niyə biz — başlıq (AZ)'),
        ),
    ]
