# Generated by Django 5.2.16 on 2026-07-22 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_why_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectgalleryimage',
            options={'ordering': ('id',), 'verbose_name': 'Qaleriya şəkli', 'verbose_name_plural': 'Qaleriya şəkilləri'},
        ),
        migrations.CreateModel(
            name='AppealContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Ad və soyad')),
                ('phone', models.CharField(max_length=40, verbose_name='Nömrə')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('service_name', models.CharField(blank=True, default='', help_text='Formadan gələn xidmət adı (snapshot) — xidmət silinsə belə qalır.', max_length=160, verbose_name='Xidmət adı')),
                ('source', models.CharField(blank=True, choices=[('home', 'Ana səhifə'), ('contact_page', 'Əlaqə səhifəsi'), ('service_modal', 'Xidmət modalı')], default='', help_text='Ana səhifə / Əlaqə səhifəsi / Xidmət modalı — POST sonra doldurulacaq.', max_length=32, verbose_name='Mənbə')),
                ('is_read', models.BooleanField(default=False, help_text='Müraciəti oxuduqdan sonra işarələyin.', verbose_name='Oxunub?')),
                ('is_customer', models.BooleanField(default=False, help_text='Bu şəxs müştəri olubsa işarələyin.', verbose_name='Müştərimizdir?')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete — siyahıdan gizlətmək üçün.', verbose_name='Silinib?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='core.service', verbose_name='Xidmət')),
            ],
            options={
                'verbose_name': 'Müraciət',
                'verbose_name_plural': 'Saytdan gələn müraciətlər',
                'ordering': ('-created_at',),
            },
        ),
    ]
