# Generated by Django 5.2.16 on 2026-07-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_appeal_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appealcontact',
            name='service',
        ),
        migrations.RemoveField(
            model_name='appealcontact',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='appealcontact',
            name='source',
        ),
    ]
