# Generated by Django 5.2.16 on 2026-07-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_consultation_appeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appealcontact',
            name='source',
        ),
    ]
