# Generated by Django 5.2.16 on 2026-07-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_appeal_contact_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationappeal',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Xidmət adı'),
        ),
    ]
