# Generated by Django 5.2.16 on 2026-07-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_consultation_appeal_admin_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appealcontact',
            name='is_deleted',
        ),
    ]
