# Generated by Django 6.0.7 on 2026-07-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_appeal_contact_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageorder',
            name='package_name',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Paket adı'),
        ),
    ]
