# Generated by Django 5.2.16 on 2026-07-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_package_order_remove_package_name_help'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='show_in_footer',
        ),
        migrations.AlterField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=False, help_text='İşarələsəniz rəy saytda görünər.', verbose_name='Təsdiq et'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Oxunmuş et'),
        ),
    ]
