# Generated by Django 5.2.16 on 2026-07-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_package_show_in_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_az', models.TextField(blank=True, help_text='Mətn yazılsa saytda səhifə və footer keçidi görünəcək; boş saxlansa keçid/səhifə məzmunu göstərilməyəcək.', verbose_name='İstifadə şərtləri (AZ)')),
                ('terms_en', models.TextField(blank=True, null=True, verbose_name='İstifadə şərtləri (EN)')),
                ('terms_ru', models.TextField(blank=True, null=True, verbose_name='İstifadə şərtləri (RU)')),
                ('privacy_az', models.TextField(blank=True, help_text='Mətn yazılsa saytda səhifə və footer keçidi görünəcək; boş saxlansa keçid/səhifə məzmunu göstərilməyəcək.', verbose_name='Məxfilik siyasəti (AZ)')),
                ('privacy_en', models.TextField(blank=True, null=True, verbose_name='Məxfilik siyasəti (EN)')),
                ('privacy_ru', models.TextField(blank=True, null=True, verbose_name='Məxfilik siyasəti (RU)')),
            ],
            options={
                'verbose_name': 'Şərtlər və məxfilik',
                'verbose_name_plural': 'Şərtlər və məxfilik',
            },
        ),
    ]
