# Generated by Django 5.2.16 on 2026-07-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_legal_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalcontent',
            name='privacy_az',
            field=models.TextField(blank=True, help_text='Bu mətn doldurulsa footer-də «Məxfilik» keçidi və /privacy/ səhifəsi görünəcək. Boş saxlansa və ya bu bölmə ümumiyyətlə yaradılmasa — footer-də «Məxfilik» sözü olmaz, səhifə də göstərilməz.', verbose_name='Məxfilik siyasəti (AZ)'),
        ),
        migrations.AlterField(
            model_name='legalcontent',
            name='terms_az',
            field=models.TextField(blank=True, help_text='Bu mətn doldurulsa footer-də «Şərtlər» keçidi və /terms/ səhifəsi görünəcək. Boş saxlansa və ya bu bölmə ümumiyyətlə yaradılmasa — footer-də «Şərtlər» sözü olmaz, səhifə də göstərilməz.', verbose_name='İstifadə şərtləri (AZ)'),
        ),
    ]
