# Generated by Django 5.2.16 on 2026-07-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_training_sort_from_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininggalleryimage',
            name='is_cover',
            field=models.BooleanField(default=False, help_text='İşarələsəniz bu şəkil təlim kartında görünəcək. Bir təlimdə yalnız biri.', verbose_name='Kart şəkli?'),
        ),
    ]
